### ISSUE TITLE
Update typer to 0.4.0+

### ISSUE THREAD

**Issue by dhalbert** [adafruit/cascadetoml#3]
`cascadetoml` uses `typer`, which needs `click 7.x.x`. `typer` has not yet been upgraded to support click `8.x.x`: https://github.com/tiangolo/typer/issues/280. There are very recent comments there about fixing `typer`, though it has been quite a while since any PR's (including a fix for this) were merged.

The latest `circup` needs `click>=8.0.1`, so this conflicts with `typer`'s requirement.

**Comment by tiangolo** [comment]
I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada:

**Comment by tannewt** [comment]
Thanks @tiangolo! We'll update to it.
